let easyWords = [
    "Dog",
    "Cat",
    "Pizza",
    "Swimming",
    "Sleeping",
    "Driving",
    "Running",
    "Jumping",
    "Dancing",
    "Eating",
    "Drinking",
    "Crying",
    "Laughing",
    "Clapping",
    "Brushing Teeth",
    "Cooking",
    "cough", "sneeze", "laugh", "swim", "run", "jump", "piano", "baseball", "football", "guitar", "basketball", "microphone", "snake", "rabbit", "horse", "trip", "round", "stake", "state", "cowboy", "thief", "roller blading" , "half", "quarter", "light bulb", "door", "backbone", "treasure", "pirate", "whistle", "photograph", "key", "frog", "pinwheel", "battery", "song", "bomb", "garbage", "ski", "skateboard", "queen", "computer", "hot dog", "ipad", "cake", "mailman", "bicycle", "lightsaber", "bowtie", "wax", "music", "bowling", "ironing", "motorcycle", "hopscotch", "making pizza", "washing", "showering", "soccer", "football", "hailing a taxi", "raking leaves",
    "Fishing",
    "Reading",
    "Writing",
    "Climbing",
    "Skating",
    "Singing",
    "Whistling",
    "Baby",
    "Teacher",
    "Doctor",
    "Firefighter",
    "Police Officer",
    "Basketball",
    "Soccer",
    "Baseball",
    "Volleyball",
    "Snowman",
    "Superhero",
    "Ghost",
    "Robot",
    "Alien",
    "Monster",
    "Banana",
    "Apple",
    "Sandwich",
    "Ice Cream",
    "Cake",
    "Bicycle",
    "Car",
    "Train",
    "Airplane",
    "Boat",
    "Camera",
    "Guitar"
];

export default easyWords;