let easyWords = [
    "Dog",
    "Cat",
    "Pizza",
    "Swimming",
    "Sleeping",
    "Driving",
    "Running",
    "Jumping",
    "Dancing",
    "Eating",
    "Drinking",
    "Crying",
    "Laughing",
    "Clapping",
    "Brushing Teeth",
    "Cooking",
    "Fishing",
    "Reading",
    "Writing",
    "Climbing",
    "Skating",
    "Singing",
    "Whistling",
    "Baby",
    "Teacher",
    "Doctor",
    "Firefighter",
    "Police Officer",
    "Basketball",
    "Soccer",
    "Baseball",
    "Volleyball",
    "Snowman",
    "Superhero",
    "Ghost",
    "Robot",
    "Alien",
    "Monster",
    "Banana",
    "Apple",
    "Sandwich",
    "Ice Cream",
    "Cake",
    "Bicycle",
    "Car",
    "Train",
    "Airplane",
    "Boat",
    "Camera",
    "Guitar"
];

export default easyWords;