let hardWords = [
    "Acting In A Movie",
    "Adopting A Pet",
    "Air Traffic Control",
    "Aircraft",
    "Airplane Landing",
    "Alien Abduction",
    "Alien Invasion",
    "America",
    "Ancient Curse",
    "Ancient Egypt",
    "Apocalypse Survivor",
    "Armageddon",
    "Artificial Intelligence",
    "Avatar",
    "Baby Shark",
    "Baking Bread",
    "Balancing On A Tightrope",
    "Bank Heist",
    "Becoming Invisible",
    "Being Chased",
    "Black Hole",
    "Black Market",
    "Blindfolded",
    "Brain Freeze",
    "Brainwash",
    "Breaking A World Record",
    "Breaking Glass",
    "Broken Reality",
    "Building A Rocket",
    "Building A Sandcastle",
    "Bungee Jumping",
    "Burp",
    "Carrot",
    "Catching A Thief",
    "Cave Exploring",
    "Changing A Tire",
    "Chasing Tornados",
    "Climbing A Ladder",
    "Climbing Mount Everest",
    "Cloning Yourself",
    "Clumsy",
    "Coal",
    "Conducting An Orchestra",
    "Cooking A Fancy Meal",
    "Couch Surfing",
    "Crashing A Party",
    "Creating A Robot",
    "Crossing A Bridge",
    "Cyber Attack",
    "Dancing In The Rain",
    "Dark Ritual",
    "Decoding A Message",
    "Deep",
    "Defusing A Bomb",
    "Delivering A Package",
    "Digging A Hole",
    "Dimension Shift",
    "Disguising Yourself",
    "Dodging Lasers",
    "Dominoes",
    "Donut",
    "Double Agent",
    "Dragon Battle",
    "Dream Loop",
    "Dreaming",
    "Driving A Race Car",
    "Eagle",
    "Earthquake",
    "Electricity",
    "Energy Control",
    "Energy Drain",
    "Escaping A Maze",
    "Escaping Prison",
    "Exploring A Jungle",
    "Falling In Love",
    "False Reality",
    "Feeding Animals",
    "Fighting A Villain",
    "Filming",
    "Finding A Secret Door",
    "Finding Treasure",
    "Finger Painting",
    "Fixing A Computer",
    "Flip",
    "Flying A Helicopter",
    "Flying A Kite",
    "Flying Through Space",
    "Food Fight",
    "Freezing Time",
    "Future Vision",
    "Gardening",
    "Getting Lost",
    "Ghost Whispering",
    "Gingerbread Man",
    "Going Viral",
    "Gravity Loss",
    "Guarding Treasure",
    "Gymnast",
    "Hacking A Computer",
    "Harry Potter",
    "Haunted House",
    "Helicopter",
    "Hiccup",
    "Hidden Powers",
    "Hidden Truth",
    "Hiding From Monsters",
    "Hockey",
    "Holding Your Breath",
    "Identity Crisis",
    "Identity Theft",
    "Inception",
    "Inner Demons",
    "Inventing Something",
    "Jello",
    "Joke",
    "Journal",
    "Jumping Over Obstacles",
    "Jurassic Park",
    "Karaoke",
    "Landing A Plane",
    "Launching A Rocket",
    "Lawnmower",
    "Leading A Team",
    "Learning",
    "Life Drain",
    "Living In Space",
    "Lord Of The Rings",
    "Lost Identity",
    "Lost In The Desert",
    "Lost Memory",
    "Mad Scientist",
    "Magic Duel",
    "Magic Trick",
    "Making A Potion",
    "Mattress",
    "Measuring Time",
    "Medieval Knight",
    "Memory Loss",
    "Memory Swap",
    "Mental Prison",
    "Milking A Cow",
    "Mime",
    "Mind Control",
    "Mind Reading",
    "Mission Impossible",
    "Model",
    "Moral Dilemma",
    "Mosquito",
    "Multiple Personalities",
    "Nature",
    "Negotiating",
    "Olympics",
    "Onion",
    "Opening A Portal",
    "Outrunning Danger",
    "Outside",
    "Painting A Masterpiece",
    "Palace",
    "Paradox",
    "Parallel Universe",
    "Park",
    "Parkour",
    "Party Pooper",
    "Password",
    "Past Life",
    "Performing On Stage",
    "Phantom Pain",
    "Piloting A Spaceship",
    "Pirate Treasure",
    "Platypus",
    "Play With Toys",
    "Playing Chess",
    "Playing The Violin",
    "Power Surge",
    "Predicting The Future",
    "Protecting Someone",
    "Pulling A Sword From Stone",
    "Putting Up A Tent",
    "Quantum Leap",
    "Rapid Aging",
    "Reality Glitch",
    "Reality Shift",
    "Rescuing Someone",
    "Reverse Aging",
    "Riding A Carousel",
    "Riding A Dragon",
    "Road Rage",
    "Robot Uprising",
    "Rock Climbing",
    "Roller Coaster",
    "Rotten",
    "Running A Marathon",
    "Running From Danger",
    "Sailing",
    "Salt And Pepper",
    "Sandcastle",
    "Sauce",
    "Saving The World",
    "Scolding",
    "Scooter",
    "Scuba Diving",
    "Searching For Clues",
    "Secret Agent",
    "Secret Code",
    "Secret Identity",
    "Secret Society",
    "Self Destruct",
    "Sewing A Button",
    "Shadow Walking",
    "Shallow",
    "Shape Shifter",
    "Shape Shifting",
    "Shopping",
    "Silent Communication",
    "Simulated Reality",
    "Skull",
    "Skydiving",
    "Sneaking Into A Building",
    "Snowboard",
    "Snowboarding",
    "Solving A Mystery",
    "Solving A Puzzle",
    "Soul Transfer",
    "Space Drift",
    "Space Mission",
    "Spare",
    "Speaking Another Language",
    "Spider-Man",
    "Spring",
    "Spying",
    "Star Wars",
    "Stinky",
    "Stolen Identity",
    "Stopping Time",
    "Super Strength",
    "Surviving A Shark Attack",
    "Surviving A Storm",
    "Surviving On A Desert Island",
    "Talking To Animals",
    "Talking To Ghosts",
    "Teapot",
    "Telepathic Link",
    "Teleportation",
    "The Dark Knight",
    "The Matrix",
    "Time Collapse",
    "Time Freeze",
    "Time Loop",
    "Time Paradox",
    "Time Reversal",
    "Time Travel",
    "Titanic",
    "Toast",
    "Training For Battle",
    "Turning Invisible",
    "Undercover Mission",
    "Underwater City",
    "Unknown Signal",
    "Unlocking A Door",
    "Vanishing Act",
    "Virtual World",
    "Volcano Eruption",
    "Walk The Dog",
    "Walking On The Moon",
    "Walking Walls",
    "Warp Speed",
    "Watering A Garden",
    "Whisk",
    "Wild West",
    "Winning A Race",
    "Winning The Lottery",
    "Working Undercover",
    "Wrestling",
    "Zero Gravity",
    "Zombie Apocalypse",
];

export default hardWords;