let hardWords = [
    "Inception",
    "The Matrix",
    "Jurassic Park",
    "Harry Potter",
    "Titanic",
    "Spider-Man",
    "The Dark Knight",
    "Star Wars",
    "Lord of the Rings",
    "Avatar",
    "sailing", "carrot", "wrestling", "learning", "gardening", "scolding", "walk the dog", "donut", "Olympics", "journal", "karaoke", "play with toys", "scooter", "helicopter", "park", "dominoes", "hockey", "salt and pepper", "whisk", "mattress", "spring", "toast", "joke", "sauce", "coal", "aircraft", "electricity", "password", "teapot", "nature", "outside", "gingerbread man", "spare", "platypus", "snowboard", "palace", "lawnmower", "deep", "shallow", "America", "food fight", "shopping", "filming", "finger painting", "watering a garden", "feeding animals", "rock climbing", "flying a kite", "chasing tornados", "sewing a button", "scuba diving", "riding a carousel", "baking bread", "flip", "sandcastle", "putting up a tent", "airplane landing", "onion", "skull",
    "Time Travel",
    "hiccup", "burp", "road rage", "mad scientist", "stinky", "model", "rotten", "mime", "clumsy", "baby shark", "gymnast", "party pooper", "jello", "mosquito", "milking a cow",
    "Zombie Apocalypse",
    "Winning the Lottery",
    "Breaking a World Record",
    "Climbing Mount Everest",
    "Running a Marathon",
    "Finding Treasure",
    "Escaping Prison",
    "Solving a Mystery",
    "Walking on the Moon",
    "Surviving a Shark Attack",
    "Building a Rocket",
    "Flying a Helicopter",
    "Defusing a Bomb",
    "Playing the Violin",
    "Conducting an Orchestra",
    "Snowboarding",
    "Skydiving",
    "Bungee Jumping",
    "Roller Coaster",
    "Haunted House",
    "Magic Trick",
    "Becoming Invisible",
    "Talking to Animals",
    "Mind Reading",
    "Super Strength",
    "Teleportation",
    "Couch Surfing",
    "Underwater City",
    "Robot Uprising",
    "Alien Invasion",
    "Lost in the Desert",
    "Surviving on a Desert Island",
    "Ancient Egypt",
    "Medieval Knight",
    "Pirate Treasure",
    "Wild West",
    "Secret Agent",
    "Space Mission",
    "Volcano Eruption",
    "Earthquake"
];

export default hardWords;