let hardWords = [
    "Inception",
    "The Matrix",
    "Jurassic Park",
    "Harry Potter",
    "Titanic",
    "Spider-Man",
    "The Dark Knight",
    "Star Wars",
    "Lord of the Rings",
    "Avatar",
    "Time Travel",
    "Zombie Apocalypse",
    "Winning the Lottery",
    "Breaking a World Record",
    "Climbing Mount Everest",
    "Running a Marathon",
    "Finding Treasure",
    "Escaping Prison",
    "Solving a Mystery",
    "Walking on the Moon",
    "Surviving a Shark Attack",
    "Building a Rocket",
    "Flying a Helicopter",
    "Defusing a Bomb",
    "Playing the Violin",
    "Conducting an Orchestra",
    "Snowboarding",
    "Skydiving",
    "Bungee Jumping",
    "Roller Coaster",
    "Haunted House",
    "Magic Trick",
    "Becoming Invisible",
    "Talking to Animals",
    "Mind Reading",
    "Super Strength",
    "Teleportation",
    "Couch Surfing",
    "Underwater City",
    "Robot Uprising",
    "Alien Invasion",
    "Lost in the Desert",
    "Surviving on a Desert Island",
    "Ancient Egypt",
    "Medieval Knight",
    "Pirate Treasure",
    "Wild West",
    "Secret Agent",
    "Space Mission",
    "Volcano Eruption",
    "Earthquake"
];

export default hardWords;