hardWords = [
    "Air Guitar",
    "Airplane",
    "Alarm Clock",
    "Alien",
    "Alligator",
    "Angry",
    "Apple",
    "Arcade",
    "Arm Wrestling",
    "Baby",
    "Backbone",
    "Backflip",
    "Balloon",
    "Banana",
    "Barking",
    "Baseball",
    "Basketball",
    "Battery",
    "Beach",
    "Bee",
    "Belly Laugh",
    "Bicycle",
    "Bird",
    "Blowing Bubbles",
    "Blowing Wind",
    "Boat",
    "Bomb",
    "Book",
    "Bored",
    "Bowling",
    "Bowtie",
    "Boxing",
    "Breakdancing",
    "Broom",
    "Brushing Teeth",
    "Bubble Bath",
    "Building",
    "Bus",
    "Cake",
    "Camera",
    "Camping",
    "Candle",
    "Candy",
    "Car",
    "Car Wash",
    "Cartwheel",
    "Cat",
    "Catching",
    "Chair",
    "Cheering",
    "Chicken",
    "Chopping Wood",
    "Clapping",
    "Climbing",
    "Clock",
    "Cloud",
    "Cold",
    "Computer",
    "Confused",
    "Cooking",
    "Cough",
    "Cowboy",
    "Crawling",
    "Crying",
    "Dancing",
    "Dizzy",
    "Doctor",
    "Dog",
    "Dolphin",
    "Door",
    "Dragon",
    "Drawing",
    "Drinking",
    "Driving",
    "Drumming",
    "Duck",
    "Eating",
    "Elephant",
    "Escalator",
    "Excited",
    "Exercise",
    "Falling",
    "Fan",
    "Farmer",
    "Fast",
    "Feeding",
    "Finger Painting",
    "Firefighter",
    "Fishing",
    "Floating",
    "Flower",
    "Flying",
    "Football",
    "Frog",
    "Funny",
    "Game",
    "Garbage",
    "Gardening",
    "Ghost",
    "Giraffe",
    "Giving Gift",
    "Glasses",
    "Gold",
    "Gorilla",
    "Grocery Shopping",
    "Guitar",
    "Hailing A Taxi",
    "Haircut",
    "Half",
    "Hammer",
    "Happy",
    "Hat",
    "Helicopter",
    "Hiding",
    "Hiking",
    "Holding Baby",
    "Hopscotch",
    "Horse",
    "Hot Dog",
    "Hungry",
    "Ice Cream",
    "Ice Skating",
    "Injured",
    "Ipad",
    "Ironing",
    "Juggling",
    "Jump",
    "Jumping",
    "Kangaroo",
    "Key",
    "Knocking",
    "Laugh",
    "Laughing",
    "Laughing Hard",
    "Light Bulb",
    "Lightsaber",
    "Lion",
    "Magic Trick",
    "Mailman",
    "Making Pizza",
    "Marching",
    "Measuring",
    "Meditating",
    "Microphone",
    "Mirror",
    "Monster",
    "Mopping",
    "Motorcycle",
    "Mouse",
    "Music",
    "Nap",
    "Nervous",
    "Octopus",
    "Painting",
    "Panda",
    "Penguin",
    "Phone",
    "Photograph",
    "Piano",
    "Picking Apples",
    "Pinwheel",
    "Pirate",
    "Pizza",
    "Plant",
    "Playing Cards",
    "Playing Drums",
    "Playing Violin",
    "Police Officer",
    "Pulling",
    "Pushing",
    "Quarter",
    "Queen",
    "Rabbit",
    "Rain",
    "Rainbow",
    "Raking Leaves",
    "Reading",
    "Riding Horse",
    "Robot",
    "Rock Climbing",
    "Roller Blading",
    "Round",
    "Run",
    "Running",
    "Sailing",
    "Sandwich",
    "Scared",
    "Scooter",
    "Searching",
    "Shark",
    "Shopping",
    "Showering",
    "Shy",
    "Singing",
    "Sitting",
    "Skateboard",
    "Skating",
    "Ski",
    "Skipping",
    "Sleeping",
    "Slow Motion",
    "Snake",
    "Sneaking",
    "Sneeze",
    "Snowman",
    "Soccer",
    "Song",
    "Spider",
    "Spinning",
    "Squirrel",
    "Stake",
    "Standing",
    "Stargazing",
    "State",
    "Stretching",
    "Superhero",
    "Surprised",
    "Sweeping",
    "Swim",
    "Swimming",
    "Swing",
    "Taking Selfie",
    "Talking",
    "Taxi",
    "Teacher",
    "Tennis",
    "Thief",
    "Thinking",
    "Throwing",
    "Tickling",
    "Tiger",
    "Tired",
    "Toothbrush",
    "Tornado",
    "Train",
    "Treasure",
    "Tree",
    "Trip",
    "Typing",
    "Umbrella",
    "Vacuuming",
    "Volleyball",
    "Walking Dog",
    "Washing",
    "Waterfall",
    "Wave",
    "Waving",
    "Wax",
    "Weightlifting",
    "Whistle",
    "Whistling",
    "Winking",
    "Wizard",
    "Writing",
    "Alien Abduction",
    "Black Market",
    "Breaking Reality",
    "Chasing Dreams",
    "Climbing Mountain",
    "Cracking Safe",
    "Cyber Attack",
    "Double Agent",
    "Dream Loop",
    "Escaping Prison",
    "Fighting Villain",
    "Finding Clues",
    "Flying Spaceship",
    "Future Vision",
    "Hiding Identity",
    "Jumping Obstacles",
    "Landing Plane",
    "Magic Duel",
    "Mind Reading",
    "Opening Portal",
    "Parkour Run",
    "Pulling Sword",
    "Rescue Mission",
    "Riding Dragon",
    "Running Danger",
    "Secret Mission",
    "Shapeshifting",
    "Sneaking Around",
    "Solving Puzzle",
    "Space Drift",
    "Spy Mission",
    "Stopping Time",
    "Surviving Storm",
    "Sword Fighting",
    "Talking Ghosts",
    "Teleportation",
    "Time Travel",
    "Undercover Agent",
    "Unlocking Door",
    "Warp Speed",
    "Walking Walls",
    "Winning Battle",
    "Yawning",
    "Zombie"
]

words = set([word.title() for word in hardWords])

sorted_hardWords = sorted(words)

for word in sorted_hardWords:
    print(f"\"{word.title()}\",")