hardWords = [
    "Aircraft",
    "Airplane Landing",
    "Alien Invasion",
    "America",
    "Ancient Egypt",
    "Avatar",
    "Baby Shark",
    "Baking Bread",
    "Becoming Invisible",
    "Breaking A World Record",
    "Building A Rocket",
    "Bungee Jumping",
    "Burp",
    "Carrot",
    "Chasing Tornados",
    "Climbing Mount Everest",
    "Clumsy",
    "Coal",
    "Conducting An Orchestra",
    "Couch Surfing",
    "Deep",
    "Defusing A Bomb",
    "Dominoes",
    "Donut",
    "Eagle",
    "Earthquake",
    "Electricity",
    "Escaping Prison",
    "Feeding Animals",
    "Filming",
    "Finding Treasure",
    "Finger Painting",
    "Flip",
    "Flying A Helicopter",
    "Flying A Kite",
    "Food Fight",
    "Gardening",
    "Gingerbread Man",
    "Gymnast",
    "Harry Potter",
    "Haunted House",
    "Helicopter",
    "Hiccup",
    "Hockey",
    "Inception",
    "Jello",
    "Joke",
    "Journal",
    "Jurassic Park",
    "Karaoke",
    "Lawnmower",
    "Learning",
    "Lord Of The Rings",
    "Lost In The Desert",
    "Mad Scientist",
    "Magic Trick",
    "Mattress",
    "Medieval Knight",
    "Milking A Cow",
    "Mime",
    "Mind Reading",
    "Model",
    "Mosquito",
    "Nature",
    "Olympics",
    "Onion",
    "Outside",
    "Palace",
    "Park",
    "Party Pooper",
    "Password",
    "Pirate Treasure",
    "Platypus",
    "Play With Toys",
    "Playing The Violin",
    "Putting Up A Tent",
    "Riding A Carousel",
    "Road Rage",
    "Robot Uprising",
    "Rock Climbing",
    "Roller Coaster",
    "Rotten",
    "Running A Marathon",
    "Sailing",
    "Salt And Pepper",
    "Sandcastle",
    "Sauce",
    "Scolding",
    "Scooter",
    "Scuba Diving",
    "Secret Agent",
    "Sewing A Button",
    "Shallow",
    "Shopping",
    "Skull",
    "Skydiving",
    "Snowboard",
    "Snowboarding",
    "Solving A Mystery",
    "Space Mission",
    "Spare",
    "Spider-Man",
    "Spring",
    "Star Wars",
    "Stinky",
    "Super Strength",
    "Surviving A Shark Attack",
    "Surviving On A Desert Island",
    "Talking To Animals",
    "Teapot",
    "Teleportation",
    "The Dark Knight",
    "The Matrix",
    "Time Travel",
    "Titanic",
    "Toast",
    "Underwater City",
    "Volcano Eruption",
    "Walk The Dog",
    "Walking On The Moon",
    "Watering A Garden",
    "Whisk",
    "Wild West",
    "Winning The Lottery",
    "Wrestling",
    "Zombie Apocalypse"
]

words = set([word.title() for word in hardWords])

sorted_hardWords = sorted(words)

for word in sorted_hardWords:
    print(f"\"{word.title()}\",")